# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            wade roberts
tagline:          'evolutionary genomics'
description:      'Ph.D. Candidate at Washington State University <a href="http://twitter.com/wwaaaddddeee" target=_blank">@wwaaaddddeee</a>'
url:              http://wrroberts.github.io

author:
  name:           'Wade Roberts'
  url:            https://twitter.com/wwaaaddddeee

# paginate:         5

# Custom vars
# version:          2.1.0

github:
  repo:           https://github.com/wrroberts/wrroberts.github.io
